wandb_version: 1

discount_factor:
  desc: null
  value: 0.98
estimation_step:
  desc: null
  value: 20
target_update_freq:
  desc: null
  value: 1000
optminizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.00016
same_policy:
  desc: null
  value: true
load_model:
  desc: null
  value: false
freeze_CNN:
  desc: null
  value: false
max_epoch:
  desc: null
  value: 500
step_per_epoch:
  desc: null
  value: 20000
step_per_collect:
  desc: null
  value: 400
episode_per_test:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 128
update_per_step:
  desc: null
  value: 0.02
tn_eps_max:
  desc: null
  value: 0.1
ts_eps_max:
  desc: null
  value: 0.01
warmup_size:
  desc: null
  value: 1
max_cycles:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707943028.403931
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 35
      4: 3.10.9
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      9:
        2: tianshou
      13: windows-amd64
