wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708144702.405713
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      3:
      - 13
      - 14
      - 23
      4: 3.11.6
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
