wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708214349.283192
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 2
      - 13
      - 14
      - 23
      4: 3.11.6
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
experiment_config:
  desc: null
  value:
    sampling_device: cpu
    train_device: cpu
    share_policy_params: true
    prefer_continuous_actions: false
    gamma: 0.9
    lr: 5.0e-05
    adam_eps: 1.0e-06
    clip_grad_norm: true
    clip_grad_val: 5
    soft_target_update: true
    polyak_tau: 0.005
    hard_target_update_frequency: 5
    exploration_eps_init: 0.8
    exploration_eps_end: 0.01
    exploration_anneal_frames: null
    max_n_iters: null
    max_n_frames: 3000000
    on_policy_collected_frames_per_batch: 6000
    on_policy_n_envs_per_worker: 1
    on_policy_n_minibatch_iters: 45
    on_policy_minibatch_size: 400
    off_policy_collected_frames_per_batch: 6000
    off_policy_n_envs_per_worker: 1
    off_policy_n_optimizer_steps: 1000
    off_policy_train_batch_size: 128
    off_policy_memory_size: 1000000
    off_policy_init_random_frames: 0
    evaluation: true
    render: true
    evaluation_interval: 18000
    evaluation_episodes: 50
    evaluation_deterministic_actions: true
    loggers:
    - wandb
    create_json: true
    save_folder: null
    restore_file: null
    checkpoint_interval: 180000
algorithm_config:
  desc: null
  value:
    share_param_critic: true
    loss_function: l2
    delay_value: true
    use_tanh_mapping: true
model_config:
  desc: null
  value:
    num_cells:
    - 256
    - 256
    layer_class: torch.nn.modules.linear.Linear
    activation_class: torch.nn.modules.activation.Tanh
    activation_kwargs: null
    norm_class: null
    norm_kwargs: null
task_config:
  desc: null
  value:
    task: b_ace
continuous_actions:
  desc: null
  value: true
on_policy:
  desc: null
  value: false
algorithm_name:
  desc: null
  value: maddpg
model_name:
  desc: null
  value: mlp
task_name:
  desc: null
  value: b_ace
environment_name:
  desc: null
  value: b_ace
seed:
  desc: null
  value: 0
